### ISSUE TITLE
Expired API Key

### ISSUE THREAD

**Issue by bakhtiyor** [googlemaps/js-samples#107]
Hello, 
None of samples given here https://storage.googleapis.com/js-samples/master/index.html is opening. I think it is due to map api key.

**Comment by jpoehnelt** [comment]
Thanks for reporting, fix in progress. Please note that some of the recently imported samples are not fully functional.

**Comment by jpoehnelt** [comment]
also see https://github.com/googlemaps/js-samples/commit/fde7e82c20b8fe12e10f4f41a3f4c38676798cd7
