### ISSUE TITLE
Error undefined /_without_region_tags.js while serving

### ISSUE THREAD

**Issue by philip-firstorder** [googlemaps/js-samples#109]
#### Environment details

1. googlemaps/js-samples
2. MacOS Catalina 10.15.3
3. devsite-2019-12-18
4. yarn -v 1.22.0

#### Steps to reproduce

1. Clone the repo, checkout the dev branch
2. export GOOGLE_MAPS_JS_SAMPLES_KEY='...' environment variable
3. `yarn run serve`

#### Stack trace
```
js-samples % yarn run serve
yarn run v1.22.0
$ bazel run :serve
INFO: Invocation ID: 590013e7-0043-4c21-985a-e3be954f98ae
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analyzed target //:serve (1 packages loaded, 12405 targets configured).
INFO: Found 1 target...
ERROR: /Users/current/Projects/googlemaps/js-samples/samples/aerial-rotation/BUILD.bazel:16:1: error executing shell command: '/bin/bash -c 
        cp $1 $2

        sed -i 's/\/\/ \[START[A-Z_]* .*\]//g' $2
        sed -i 's/\/\/ \[END[A-Z_]* .*\]//g' $2
        sed -i 's/<\!-- \[START[A-Z_]* .*\] -->//g' $2
        sed ...' failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
sed: 1: "bazel-out/darwin-fastbu ...": undefined label 'azel-out/darwin-fastbuild/bin/samples/aerial-rotation/_without_region_tags.js'
sed: 1: "bazel-out/darwin-fastbu ...": undefined label 'azel-out/darwin-fastbuild/bin/samples/aerial-rotation/_without_region_tags.js'
sed: 1: "bazel-out/darwin-fastbu ...": undefined label 'azel-out/darwin-fastbuild/bin/samples/aerial-rotation/_without_region_tags.js'
sed: 1: "bazel-out/darwin-fastbu ...": undefined label 'azel-out/darwin-fastbuild/bin/samples/aerial-rotation/_without_region_tags.js'
Target //:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by jpoehnelt** [comment]
I wasn't able to reproduce this error on Debian.

Did you have any successful builds?

```sh
undefined label 'azel-out/darwin-fastbuild/bin/samples/aerial-rotation/_without_region_tags.js'
Target //:serve failed to build
```
should be 
```sh
undefined label 'bazel-out/...'
```

🤔

**Comment by jpoehnelt** [comment]
Maybe try `npx bazel clean --expunge` and try again?

**Comment by philip-firstorder** [comment]
Ran clean command but got same error. 

I just tried it on a completely new system with a fresh MacOS Catalina and got the same error, so now I got it on 2 separate iMacs.

**Comment by philip-firstorder** [comment]
> I wasn't able to reproduce this error on Debian.
> 
> Did you have any successful builds?
> 
> ```shell
> undefined label 'azel-out/darwin-fastbuild/bin/samples/aerial-rotation/_without_region_tags.js'
> Target //:serve failed to build
> ```
> 
> should be
> 
> ```shell
> undefined label 'bazel-out/...'
> ```
> 
> 🤔

Yeah I notice that, I don't know why he is truncating that.

**Comment by jpoehnelt** [comment]
I'm going to be off for a bit(until 24th) and won't be able to get to this, but you can also try this branch: https://github.com/googlemaps/js-samples/compare/dev...experiment/ignore_strip_tags

I just removed the failing rule from. There might be another underlying issue though and I doubt this will work. It could be related to your shell????????

**Comment by philip-firstorder** [comment]
I remember I had a similar problem with `sed -i `commands before, they behave differently on MacOS and Linux.

-i '' works with OS X's sed but not GNU sed. -i works with GNU sed, recent versions of NetBSD, OpenBSD sed, but not OS X's sed. 

The best way I have found to have the same script work on both Linux and Mac is to:

```
sed -i.bak -e 's/foo/bar/' -- "${TARGET}" &&
  rm -- "${TARGET}.bak"
```

I am trying to fix it now.

**Comment by philip-firstorder** [comment]
Fixed, I opened a pull request for you to merge.

**Comment by jpoehnelt** [comment]
no longer using `sed -i`
