### ISSUE TITLE
sample-react-map branch dependencies miss "fast-equals": "^3.0.3"

### ISSUE THREAD

**Issue by Malaaaa** [googlemaps/js-samples#1205]
### Operating system

windows 11 

### Browser Version

Firefox 101.0

### How severe is the bug?

low

### Bug description

package.json missed  dependencies : "fast-equals": "^3.0.3", :) so that [Try Sample](https://developers.google.com/maps/documentation/javascript/react-map) didn't work in any platform.

### Steps to reproduce

  git clone -b sample-react-map https://github.com/googlemaps/js-samples.git
  cd js-samples
  npm i
  npm start

### Console log output

```sh
[vite] Internal server error: Failed to resolve import "fast-equals" from "index.tsx". Does the file exist?
```

**Comment by Malaaaa** [comment]
Another little thing is the key has a secure restrict plan, I don't know if this is a problem. 
Best Regards

**Comment by mnlfischer** [comment]
fast-equals release v4 and the example needs to be updated.
