### ISSUE TITLE
Bug: places-placeid-finder

### ISSUE THREAD

**Issue by beatrizsj** [googlemaps/js-samples#1224]
### Operating system

Windows

### Browser Version

Chrome 103.0.5060.114

### How severe is the bug?

high

### Bug description

Olá, hoje a Lopes Consultoria de Imóveis utiliza as APIs do Google no seu portal e encontramos alguns bugs.

As localidades Parque dos Buritis, Quinta do Buritis, Damha Golf entre outros não são reconhecidas como bairros da cidade de São Carlos. no autocomplete acaba retornando opções que são pontos de interesse que tem como endereço uma localidade incorreta.

Por exemplo: Quinta dos Buritis e Damha Golf constam como o bairro Água Vermelha.

**Comment by wangela** [comment]
Olá, por favor reporte este problema no [Places API Public Issue Tracker](https://issuetracker.google.com/issues/new?component=188872&template=787713)
