### ISSUE TITLE
Bug: places-autocomplete-hotelsearch

### ISSUE THREAD

**Issue by rkmunusamy** [googlemaps/js-samples#1308]
### Operating system

Windowa

### Browser Version

Chrome

### How severe is the bug?

moderate

### Bug description

It is loading lot of datas while opening the page

### Console log output

```sh
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by rkmunusamy** [comment]
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-hotelsearch

**Comment by rkmunusamy** [comment]
Taking time to load the content Screen has been freezed

**Comment by amuramoto** [comment]
it appears to be working as expected now

**Comment by rkmunusamy** [comment]
Thank you :-) I will test it again
