### ISSUE TITLE
About extracting a sample

### ISSUE THREAD

**Issue by Martin-Mok-Tin-Kui** [googlemaps/js-samples#291]
When I run `googlemaps-js-samples init map-simple destFolder`, I download all packages including build tools every time.   
**How can I run the `googlemaps-js-samples` using pnpm or yarn package manager** to link the previous downloaded packages instead of downloading everything?  
Can I choose the package manager with `googlemaps-js-samples`?

**Comment by jpoehnelt** [comment]
@Martin-Mok-Tin-Kui 

`googlemaps-js-samples --no-hot --no-open` should not call npm.
