### ISSUE TITLE
Remove origin property from Places Autocomplete widget samples

### ISSUE THREAD

**Issue by wangela** [googlemaps/js-samples#529]
https://github.com/googlemaps/js-samples/blob/cefcf83b0ed334e6b82e63c77bcda4259279478d/samples/places-autocomplete/src/index.ts#L41
and
https://github.com/googlemaps/js-samples/blob/cefcf83b0ed334e6b82e63c77bcda4259279478d/samples/places-autocomplete-multiple-countries/src/index.ts#L46

contain the `origin` property which is only used with the programmatic AutocompleteService.getPlacePredictions() AutocompletionRequest interface. I introduced this bug and am correcting the documentation that led me to do this. Assigning to self to fix in next PR.

**Comment by jpoehnelt** [comment]
Removing the `as google.maps.places.AutocompleteOptions;` should enforce the correct interface in TypeScript.
