### ISSUE TITLE
Places: getDetails() example doesn't appear to actually call intended code

### ISSUE THREAD

**Issue by beroff** [googlemaps/js-samples#622]
#### Environment details

2. OS type and version

Windows 8.1 Pro
Chrome 88.0.4324.190

3. Library version and other environment information

https://developers.google.com/maps/documentation/javascript/examples/place-details#maps_place_details-css
js-samples/dist/samples/place-details/sample.html Latest commit 0e26a5b on Feb 5
js-samples/dist/samples/place-details/index.js Latest commit 2bf29a1 on Feb 9
js-samples/dist/samples/place-details/style.css Latest commit c9dec93 on Aug 24, 2020

#### Steps to reproduce

I downloaded the above three files to an empty directory, then opened sample.html in Chrome.

The map correctly displays, and when I click on a place, a small info card correctly appears with the business name and address, plus a link, "View on Google Maps".  However, I noticed that that last line does not appear in the setContent() call, and the Place ID referenced in that call is not displayed.  Indeed, when I comment out almost the entirety of index.js other than the one call to google.maps.Map(), the map continues to display as described.  In other words, the following single statement yields identical functionality:

```
function initMap() {
  const map = new google.maps.Map(document.getElementById("map"), {
    center: { lat: -33.866, lng: 151.196 },
    zoom: 15,
  });
}
```

I apologize if I have missed something absolutely basic here.  My intent here was to use the example to learn more about how getDetails() works, perhaps by adding a field to the request.fields[] list and then displaying it in the infowindow.setContent() call, but because that doesn't appear to ever get called, I was not able to do this.  Thank you for your kind help in resolving my confusion.

**Comment by jpoehnelt** [comment]
I am unable to recreate any issue here. The `getDetails` call is executed and sets content on the info window activated by clicking the marker.
