### ISSUE TITLE
Satellite layer

### ISSUE THREAD

**Issue by bucibucii** [googlemaps/js-samples#63]
When using the Satellite layer, the map makes 4 other requests with Map layer, like there are open both Layers on the same time

**Comment by jpoehnelt** [comment]
Do you have a specific example of this that I can take a look at?

**Comment by bucibucii** [comment]
![Screenshot_23](https://user-images.githubusercontent.com/2406460/69318800-3ed6ed80-0c3e-11ea-8970-f1f101d82f0b.png)

**Comment by jpoehnelt** [comment]
This appears to be for the maps.google.com and not related to this repository. The multiple requests is because the data is split into tiles and each must be requested individually.

**Comment by bucibucii** [comment]
The layer selected is Satellite, the request is Terrain. Anyway!
