### ISSUE TITLE
open_now is present in payload from getPlaces even though it is deprecated

### ISSUE THREAD

**Issue by rostgoat** [googlemaps/js-samples#633]
Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title: Places
2. OS type and version: Ubuntu 20.04
3. Library version and other environment information: n/a

#### Steps to reproduce

  In my current implemention, I can see that `getPlaces` returns `opening_hours` which contains `open_now` even though this is a deprecated field. 

Even though I manually delete it from my array of place objects, I still get the warnings in the browser. Why am I still seeing this?

I specifically see these errors when I push my places array into my redux store, even though those fields are deleted.

#### Code example

```
  /**
   * Retreive seachered query from google place search
   */
  const DestinationSearchBar = ({ setSearchedPlaces }) => {
  const classes = useStyles()
  const searchBoxRef = useRef()
  const dispatch = useDispatch()

  /**
   * Retreive seachered query from google place search
   */
  const getSearchedPlacesFromGoogle = useCallback(() => {
    const input = document.getElementById('destination-search')
    const searchBox = new google.maps.places.SearchBox(input)

    /**
     * Return searched Google Place information
     */
    searchBox.addListener('places_changed', () => {
      input.value = ''
      let places = searchBox.getPlaces()
      let photosObject = {}

      places.forEach(p => {
        if (!_.isEmpty(p.photos) && p.photos.length > 0) {
          photosObject[`${p.place_id}`] = p.photos.map(photo => photo.getUrl())
        }
      })

      places = places.map(place => {
        if (photosObject[`${place.place_id}`]) {
          return {
            ...place,
            ...{ photos: photosObject[`${place.place_id}`] },
          }
        }
      })

      places = places.filter(place => !_.isNil(place))
      setSearchedPlaces(places)

      // pass an array of places ids and coordinates to the map component
      const filteredPlacesArray = places.map(place => {
        const geometry = {
          lat: place.geometry.location.lat(),
          lng: place.geometry.location.lng(),
        }

        if (place.opening_hours?.open_now) {
          delete place.opening_hours
          delete place.geometry
        }
        return {
          ...place,
          ...geometry,
        }
      })
      dispatch(addSelectedLocationItem(filteredPlacesArray))
    })
  }, [setSearchedPlaces])

  useEffect(() => {
    getSearchedPlacesFromGoogle()
  })

  return (
    <div className={classes.container}>
      <TextField
        inputRef={searchBoxRef}
        className={classes.searchBar}
        id="destination-search"
        placeholder="Enter a destination.."
        name="googleSearchQuery"
        InputProps={{
          endAdornment: (
            <InputAdornment position="end">
              <HighlightOffIcon
                style={{ cursor: 'pointer', fill: 'grey' }}
                onClick={() => (searchBoxRef.current.value = '')}
              />
            </InputAdornment>
          ),
        }}
      />
    </div>
  )
}
```

#### Stack trace
```
# example
```

![Screenshot from 2021-03-18 22-24-02](https://user-images.githubusercontent.com/22672124/111735399-3219d800-8839-11eb-8737-171e79355d5e.png)
![Screenshot from 2021-03-18 22-23-43](https://user-images.githubusercontent.com/22672124/111735401-32b26e80-8839-11eb-8713-2269b25507cb.png)

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jpoehnelt** [comment]
> Even though I manually delete it from my array of place objects, I still get the warnings in the browser. Why am I still seeing this?

You are still accessing the deprecated field which causes the warning.

`if (place.opening_hours?.open_now) {` => `if (place.opening_hours?.isOpen()) {`

**Comment by rostgoat** [comment]
the reason I put that if statement in there is to try to remove the deprecated field before pushing my data into redux. however, I still see the warning even if I do so, if statement or not.

**Comment by jpoehnelt** [comment]
I believe there are two triggers going on.

- The if statement or
- Some redux internals/reducer etc

Why not use the autocomplete widget? It will also be far cheaper if you do not need all the fields. https://developers.google.com/maps/documentation/javascript/places-autocomplete#summary-of-classes

**Comment by rostgoat** [comment]
I picked SearchBox mainly for suggested term feature since I want to be able to type "pizza in new" and get back
- pizza in new
- pizza in new york
- new york pizza place 1
- new york pizza place 2

Afaict, autocomplete doesn't offer this?

Going back to the original question, I am just curious as to how redux can be the problem when I am passing an array of filtered out results into it, specifically removing the `open_now` prop out of the objects?

is SearchBox the only Google places feature that returns queries with general suggestions (for example, if i type pizza, it will give me back results for pizza in my current latLngBounds?)

**Comment by jpoehnelt** [comment]
Ok, looked through a maze of source code to confirm.

it basically looks like:

```js
Object.defineProperty(open_hours, 'open_now', {
  get() {
    warn('open_now' is deprecated);
    // implementation
  },
  set() {
    warn('open_now' is deprecated);
    // implementation
  }
})
```
Try this.

```js
searchBox.addListener("places_changed", () => {
  const places = searchBox.getPlaces();

  const filtered = places.map(p => {
    // open_now is deprecated
    if (p.opening_hours) {
      delete p.opening_hours.open_now;
    }
    
    // utc_offset is deprecated
    delete p.utc_offset;
    
    return p;
  });
  
  console.log(filtered)

});
```

https://jsfiddle.net/v0t5pza4/8/

**Comment by rostgoat** [comment]
thanks for your help @jpoehnelt that worked for me!

**Comment by rostgoat** [comment]
Hi @jpoehnelt! It's me again and back with the same issue.

Just chatting with google support team regarding this issue here (https://issuetracker.google.com/issues/197027793) and I mentioned we spoke about this before.

Basically I am running into a problem where I am checking to see if `open_now` is present in the payload and it causes the deprecated warning to appear in the console, because I am checking for it!

Any idea why SearchBox still returns these fields?

Thanks

**Comment by jpoehnelt** [comment]
As mentioned in https://github.com/googlemaps/js-samples/issues/633#issuecomment-803172838, any access to open_now triggers the warning since it is in the getter.

**Comment by rostgoat** [comment]
Right so the solution below that you proposed earlier will technically not work anymore since now we're calling the getter.

```
    if (p.opening_hours) {
      delete p.opening_hours.open_now;
    }
```
