### ISSUE TITLE
Additional place details that Google Maps has in the live version but not in docs

### ISSUE THREAD

**Issue by rostgoat** [googlemaps/js-samples#634]
I am posting here because my SO post was closed. This is probably not the right place but I'll give it a shot.

#### Steps to reproduce

I am browsing through the Google places API docs but I am only seeing a subset of properties that I normally would see when searching for a place in Google Maps.

For example, if I type `Sandman Signature Vancouver Airport Hotel` on Google Maps, I will get back many fields that I don't see any Google Places docs like

 - 3 star hotel
 - Location Summary
 - Hotel Details
 - ammeneties
 - many more

Where are these props coming from? Are they from Google API or somewhere else? I cannot see them anywhere in the Network tab

![Screenshot from 2021-03-20 12-15-51](https://user-images.githubusercontent.com/22672124/111883032-0e0fe100-8976-11eb-8262-e963902cbf38.png)
![Screenshot from 2021-03-20 12-15-43](https://user-images.githubusercontent.com/22672124/111883033-0ea87780-8976-11eb-9f34-bc7be30fb4a4.png)
![Screenshot from 2021-03-20 12-15-32](https://user-images.githubusercontent.com/22672124/111883034-0ea87780-8976-11eb-9cd3-ce3de9d7a6f0.png)

**Comment by jpoehnelt** [comment]
This information is not provided in the API. Please submit a feature request. https://issuetracker.google.com/issues/new?component=188872&template=789309
