### ISSUE TITLE
Installation instructions failure with TypeError ?

### ISSUE THREAD

**Issue by dwr-psandhu** [googlemaps/js-samples#642]
#### Environment details
MacOS 10.15.7
npm -v  => 7.7.5

#### Steps to reproduce

 Follow the instructions on https://github.com/googlemaps/js-samples#initialize-an-app-from-a-sample

#### Code example
on this step...
```
googlemaps-js-samples init map-simple map-simple
```
#### Stack trace
Failure strikes...
```
TypeError: must call as: npm.load(callback)
    at Object.load (/Users/nsandhu/.npm-global/lib/node_modules/@googlemaps/js-samples/node_modules/npm/lib/npm.js:127:13)
    at Object.main [as handler] (/Users/nsandhu/.npm-global/lib/node_modules/@googlemaps/js-samples/cli/index.js:84:9)
```

**Comment by ariccio** [comment]
I was able to patch it out myself by eliminating the empty {} object in the call to npm.load

**Comment by jpoehnelt** [comment]
Just ran into this myself. I'll look into make this fix.

**Comment by jpoehnelt** [comment]
It is no longer necessary to use the cli tool as each sample is pushed to a branch in this repository. 

See branches having pattern:

```
sample-map-simple
sample-****
```

These branches should enable the following:

```
npm i
npm start
```
