### ISSUE TITLE
street-view overlays "toggle streetview" does not work in cloud shell example

### ISSUE THREAD

**Issue by crichmond** [googlemaps/js-samples#651]
When running the example in cloud shell, app starts up, but "toggle streetview" button does nothing

![image](https://user-images.githubusercontent.com/939476/114449869-ea1d7500-9b9a-11eb-916e-0b5a3c7b581b.png)

debub console in Chrome contains the following:

Uncaught ReferenceError: toggleStreetView is not defined
    at HTMLInputElement.onclick (?authuser=0:15)

**Comment by jpoehnelt** [comment]
Can add toggleStreetview to the export in the index.ts similar to the change in #652.
