### ISSUE TITLE
Deck.gl example requires requestRedraw on every frame

### ISSUE THREAD

**Issue by felixpalmer** [googlemaps/js-samples#766]
The Deck.gl sample requires requestRedraw to be called on every frame:

https://github.com/googlemaps/js-samples/blob/5a889720c9cb226619cd52bdcee34a35e9bc9a52/samples/webgl-deckgl/src/index.ts#L160

This is in contrast to the THREE.js example (https://github.com/googlemaps/js-samples/blob/master/samples/webgl-overlay-simple/src/index.ts)

Do you know what the underlying reason for this is? I note that when I remove the requestRedraw call from the Deck.gl example the overlay is only rendered when the map is moved, but this doesn't happen with the THREE.js example (I've tested this by removing the animation and re-enabling user interaction to match 1st sample)

**Comment by felixpalmer** [comment]
OK, I've dug into the `ThreeJSOverlayView` source and see that it also renders continuously, so I see the above comparison is false. However, I would still like to understand why it is necessary to do this, so if you have any background on this I would appreciate the input.

**Comment by jpoehnelt** [comment]
I'm not entirely sure that it is necessary to render continuously. I need to do more experimentation.
