### ISSUE TITLE
XSS vulnerability in place detail example 

### ISSUE THREAD

**Issue by ZhangYiJiang** [googlemaps/js-samples#772]
https://github.com/googlemaps/js-samples/blob/8c8a2e163d4df2279cc9aa54948b798b80d95056/samples/place-details/src/index.ts#L52

This uses string concatenation to construct HTML which appears to be displayed as-is in the infowindow. Constructing HTML this way sets the user up for XSS if `place.name` or any parts of the details contains malicious HTML (and yes, people do put HTML in unexpected names https://news.ycombinator.com/item?id=24919710). It's also just a bad idea in general, especially since the API accepts HTML nodes too. 

A few ways to fix this 

- Construct the DOM node using `document.createElement`, set `textContent` instead which lets the browser escape the content. Optionally set `style.whiteSpace = 'pre-line'` to preserve line breaks 
- Construct all DOM elements manually 
- Use a `<template>` tag to define the template HTML, construct a DOM fragment and replacing the `textContent` of the inner elements 
- Escape the name and formatted address - this is the easiest but worst option since it's still using string concat to build DOM nodes, which is just a bad idea in general

**Comment by jpoehnelt** [comment]
Thanks for reporting. Fixed with the first option.
