### ISSUE TITLE
onIdle is called continuously stuck in a loop

### ISSUE THREAD

**Issue by heliam1** [googlemaps/js-samples#946]
The impact of this is many React apps following our Google Maps docs might be running slow due to the Map's OnIdle is called continuously stuck in a loop. You can reproduce this by:

0 Install Node/NPM. Create a new project by just running npm init and installing React. Follow the tutorial at [0] to get the Sample React Map up and running.

1 Go to the Sample React Map [1]
And add a console.log between line 40 and 41 - at the start of onIdle function

2 Observe that this logging statement is fired continuously even while the web app is completely still - is this expected?
This is very noticeable when you add polygons or circles to the map, they'll flicker.

What I expect is happening is onIdle is called after the map is zoomed or panned by a user as expected. However setZoom and setCenter inside onIdle will cause the map to rezoom and repan/recenter, causing the event to fire again. 

I think this is able to be resolved by checking that the value you're about to call setZoom or setCenter with, is not === to zoom or center, respectively. I would have thought React would diff this for us though. If you can reproduce this, can just CL for this repo, and then CL for the docs with these checks for an easy resolve I think.

[0] https://developers.google.com/maps/documentation/javascript/react-map
[1] https://github.com/googlemaps/js-samples/blob/sample-react-map/src/index.tsx

**Comment by jpoehnelt** [comment]
Might also be worth raising an issue that the onIdle event shouldn't fire if no actual change occurred in setZoom or setCenter. Will take a look.

**Comment by jpoehnelt** [comment]
It's definitely the center prop. React does not do deep compare within `useEffect`. There are multiple options forward, but none are very clean.

1. use https://github.com/kentcdodds/use-deep-compare-effect and only use `LatLngLiteral`s as a dependency into the hook
2. pull out lat or lng and use these literals as dependencies for the hook
3. write a custom hook that uses `LatLng.equals()` when instance of matches a `google.maps.*` type. Still complicated as `LatLng.equals(latLngLiteral)` does not work. Similar to solution in 1.

**Comment by jpoehnelt** [comment]
Some bugs/feature requests I need to file/fix.

- Only trigger onIdle after a change (might be complicated)
- `.equals()` should support the literal version
