### ISSUE TITLE
async loading of google maps libraries with callbacks that work well in modern frameworks

### ISSUE THREAD

**Issue by lifeiscontent** [googlemaps/js-samples#958]
Google maps has been around for quite some time, but with modern frameworks like Angular,React,Vue,etc more things are being built as components,

can you guys either support the component model or add an example on how you would bootstrap the google library and continue to use it within a component?

e.g.

if I have a React component called

`<GoogleAutocomplete />`

I'd expect it to know how to bootstrap the maps API if needed and if I had 2+ of these components it should know how to only load the google maps API 1 time.

is there any plan to support this kind of work flow? or are you guys planing on making a npm package of google maps which can be used like this?

any help would be much appreciated.

Thanks!

**Comment by jpoehnelt** [comment]
You are in luck! Check out the following libraries I have published:

* [@googlemaps/js-api-loader](https://www.npmjs.com/package/@googlemaps/js-api-loader) - dynamic loading returning a promise, uses a singleton pattern so can be called multiple times from different components
* [@googlemaps/react-wrapper](https://www.npmjs.com/package/@googlemaps/react-wrapper) - wrapper component for react apps. uses @googlemaps/js-api-loader
* [@types/google.maps](https://www.npmjs.com/package/@types/google.maps) - for TypeScript users, automatically published
* [@googlemaps/typescript-guards](https://www.npmjs.com/package/@googlemaps/typescript-guards) - helpers for narrowing some of the unions (latlng/latlngliteral, etc)

**Comment by jpoehnelt** [comment]
Also:

* [@googlemaps/jest-mocks](https://www.npmjs.com/package/@googlemaps/jest-mocks)

**Comment by lifeiscontent** [comment]
@jpoehnelt you rock, thank you!

**Comment by jpoehnelt** [comment]
Let me know if there are any other gaps you would be like addressed.
