### ISSUE TITLE
YOUR_API_KEY not being replaced with .env value

### ISSUE THREAD

**Issue by Bjorn-Eric-Abr** [googlemaps/js-samples#964]
... and Maps requests contains `&key=YOUR_API_KEY`.

Manually replacing `YOUR_API_KEY` with the actual Api key and everything works fine.
`<Wrapper apiKey={'AIzaSyD...'} render={render}>`

Branch: sample-react-map

Running on Mac, Node v v14.18.1 and NPM 8.1.1

**Comment by jpoehnelt** [comment]
Probably need to add `tsx` to `test: /\.(ts|js)$/,` in the webpack config. Fix incoming!
