### ISSUE TITLE
Javascript Map API 

### ISSUE THREAD

**Issue by antonpious** [googlemaps/js-samples#974]
#### Steps to reproduce

  1.  Following the code as present in https://github.com/googlemaps/js-samples/blob/fab0e9b89b342866766b31dd886f5d0887ff1e51/dist/samples/programmatic-load/index.js#L6-L17
  

#### Code example

```map = new google.maps.Map(document.getElementById("map")
# example
```

#### Stack trace
```
Error message google is not defined.  
```
Where is this declared? Is it possible not to have a global scope loaded?

**Comment by jpoehnelt** [comment]
Code can only reference `google.maps` when the promise has resolved and not until then.

**Comment by antonpious** [comment]
Even if google.maps is referenced only after the promise has resolved. There should some a typedef that you should have that resemble google.maps. Where is this package? I am not able to reopen the issue.

**Comment by jpoehnelt** [comment]
https://www.npmjs.com/package/@types/google.maps is what you want.

```
npm i -D @types/google.maps
```
