### ISSUE TITLE
Javascript Map API using Async Await

### ISSUE THREAD

**Issue by antonpious** [googlemaps/js-samples#975]
Follow the code as present in https://github.com/googlemaps/js-samples/blob/fab0e9b89b342866766b31dd886f5d0887ff1e51/dist/samples/programmatic-load/index.js#L6-L17

Can this sample be updated using Async Await instead of a promise?

**Comment by jpoehnelt** [comment]
Using await should be similar to the following. 

```js
try {
  await loader.load();

  map = new google.maps.Map(document.getElementById("map"), { 
     center: { lat: -34.397, lng: 150.644 }, 
     zoom: 8, 
  });
} catch (e) {
  // handle
} 
```

**Comment by antonpious** [comment]
I was expecting you would update the documentation with this code sample too. Can you please do the same...
