### ISSUE TITLE
Contents load many many times

### ISSUE THREAD

**Issue by patrinoua** [googlemaps/js-samples#978]
Thanks for stopping by to let us know something could be better!
<img width="1792" alt="Screenshot 2022-01-09 at 04 27 58" src="https://user-images.githubusercontent.com/36475005/148666784-7bf5b99c-8c19-4383-a409-329b6d3e44c8.png">

Contents load many many times and there is no obvious way to open the demo

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version
3. Library version and other environment information

#### Steps to reproduce

  1. ?

#### Code example

```
# example
```

#### Stack trace
```
# example
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jpoehnelt** [comment]
Currently reworking all of this. See `next` branch and #996.
